# Generated by Django 5.2.8 on 2025-11-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('technology_stack', models.CharField(blank=True, max_length=300)),
                ('documentation_url', models.URLField(blank=True)),
                ('repository_url', models.URLField(blank=True)),
                ('published_date', models.DateField(blank=True)),
            ],
        ),
    ]
