# Generated by Django 5.1.4 on 2025-11-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_meta', models.CharField(max_length=100)),
                ('vezes_na_semana', models.IntegerField()),
                ('porgentagem_feita', models.FloatField(default=0)),
            ],
        ),
    ]
