# Generated by Django 5.1.4 on 2025-12-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo_Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('concluida', models.BooleanField(default=False)),
                ('vezes_na_semana', models.IntegerField()),
                ('feitas_na_semana', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registro_diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(blank=True, max_length=50, null=True)),
                ('registro', models.CharField(blank=True, max_length=50, null=True)),
                ('segunda', models.BooleanField(default=False)),
                ('terca', models.BooleanField(default=False)),
                ('quarta', models.BooleanField(default=False)),
                ('quinta', models.BooleanField(default=False)),
                ('sexta', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Registro_diario', to='semanas.objetivo_semana')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
