# Generated by Django 5.1.4 on 2025-11-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semanas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='metaModel',
            new_name='Meta_model',
        ),
    ]
