# Generated by Django 5.1.4 on 2025-12-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semanas', '0002_rename_metamodel_meta_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta_model',
            name='porgentagem_feita',
        ),
    ]
