# Generated by Django 5.1.4 on 2025-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanas', '0003_remove_meta_model_porgentagem_feita'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta_model',
            name='feitas_na_semana',
            field=models.IntegerField(default=0),
        ),
    ]
