# Generated by Django 5.1.4 on 2025-12-08 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanas', '0004_meta_model_feitas_na_semana'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta_model',
            new_name='MetaObjetivo',
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('concluido', models.BooleanField(default=False)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='semanas.metaobjetivo')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('meta', 'data')},
            },
        ),
    ]
