# Generated by Django 5.1.4 on 2025-12-09 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanas', '0005_rename_meta_model_metaobjetivo_registrodiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segunda', models.BooleanField(default=False)),
                ('terca', models.BooleanField(default=False)),
                ('quarta', models.BooleanField(default=False)),
                ('quinta', models.BooleanField(default=False)),
                ('sexta', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('concluido', models.BooleanField(default=False)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='semanas.metaobjetivo')),
            ],
            options={
                'ordering': ['-data_inicio'],
                'unique_together': {('meta', 'data_inicio')},
            },
        ),
        migrations.DeleteModel(
            name='RegistroDiario',
        ),
    ]
