# Generated by Django 5.1.4 on 2025-12-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanas', '0006_registrosemana_delete_registrodiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo_Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('concluida', models.BooleanField(default=False)),
                ('vezes_na_semana', models.IntegerField()),
                ('feitas_na_semana', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
