# Generated by Django 5.1.4 on 2025-12-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanas', '0007_objetivo_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo_semana',
            name='feitas_na_semana',
            field=models.IntegerField(default=0),
        ),
    ]
