# Generated by Django 5.1.4 on 2025-12-10 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanas', '0008_alter_objetivo_semana_feitas_na_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(max_length=50)),
                ('registro', models.CharField(max_length=50)),
                ('segunda', models.BooleanField(default=False)),
                ('terca', models.BooleanField(default=False)),
                ('quarta', models.BooleanField(default=False)),
                ('quinta', models.BooleanField(default=False)),
                ('sexta', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Registro_diario', to='semanas.objetivo_semana')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
