# Generated by Django 5.1.4 on 2025-12-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanas', '0009_registro_diario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_diario',
            name='dia_da_semana',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registro_diario',
            name='registro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
